### ISSUE TITLE
header missing

### ISSUE THREAD

**Issue by 50thomatoes50** [SoapyMan/driver_psx_level#3]
header missing make your work not understandable.
I try to make them my self but it's really hard.
You done a really god job.

**Comment by SoapyMan** [comment]
This code missing many headers because it's a part of my game engine. Which headers it missing?
Looks like I should rewrite code to complete remove these dependencies

**Comment by 50thomatoes50** [comment]
Thank you for the quick replay.
I'm trying to modify your work to export for a game which support assembled mesh

Here are all missing headers
```
core_base_header.h
DebugInterface.h
VirtualStream.h
cmdlib.h
ImageLoader.h
IFileSystem.h
core_base_header.h
utils/dklist.h
utils/eqstring.h
dktypes.h
math/vector.h
```

the utils headers are for the DkCore.dll ???

**Comment by SoapyMan** [comment]
Please see the branch "remove_deps", I have stripped some of my dependencies

**Comment by 50thomatoes50** [comment]
Thank you very much for taking time to go back on this project.
I will try to modify the code to compile under MINGW too.
